### ISSUE TITLE
Searching for ";" inserts ";" in the document

### ISSUE THREAD

**Issue by hekto** [thousandtyone/autoend#1]
I'm on Mac. <kbd>Cmd</kbd>-<kbd>F</kbd>, and then type "foo;" in the search box. It will search for "foo", but the semicolon will be inserted in the current document at the cursor.

Expected behaviour would be to search for "foo;" and not modify the document.

**Comment by thousandtyone** [comment]
Thanks so much for reporting this. This is actually a nice catch. Will try and fix this in the next 48 hours and will post a new version. Will also comment here as soon as it's done.

**Comment by thousandtyone** [comment]
Ok, so I looked at this and it looks like VS Code API seems to have a bit of a problem where it considers the Find Dialogue as the Active Text Editor (which is why it's firing the plugin activation even when you are typing in the Find Dialog box). To make things worse VS Code doesn't seem to provide any API methods which would let me find out if the Find Dialog box is open. If it did, I could selectively stop the plugin from getting activated. I've filed this question for the VS Code team: http://stackoverflow.com/questions/42447574/visual-studio-code-api-how-to-find-out-if-the-find-dialog-is-open based on their GitHub recommendation and am waiting to hear back from them.
In the meantime I'll try my level best to see if I can hack some quick solution to overcome the issue but I suspect this will take some time. Will keep you posted.

**Comment by thousandtyone** [comment]
I do realise this is not a solution and I'm going to keep the issue open, but as a workaround, for searching, if you copy a semicolon and paste it in the search dialog VS code will not consider that keybinding and will let you search for semi-colons. This would let you search for semi-colons without inserting them in the current code editor.

Given the way VS Code keybindings works, I'm having a hard time making VS Code differentiate between a semi-colon as a part of the search term and a key-binding for a command. I'll continue to look at a long term solution, but for now the copy-paste of semi-colons in the search dialog box should let you work around this issue.

Hope this helps.

**Comment by thousandtyone** [comment]
We've just checked in the changes and this should now be fixed. We've also published our changes in the VS Code Market Place so you can grab a new version of the extension directly from there.

I was able to reproduce the issue you mentioned on Linux and am able to verify that you can now search for text which contains a semi-colon using the Find dialog box (without having the plugin automatically and wrongly modify the open document instead). So from my side this looks fixed.

Unfortunately I cannot test this on a Mac since I am on a Linux machine. It'll be good if you can validate this is now fixed and let us know here, so we can go ahead and close this issue.

To test the fix you can:
1. Uninstall the plugin.
2. Install the Latest version. [The exact version where this is fixed should be 1.0.8].
3. Close VS Code.
4. Start VS Code fresh and test.

Again, thanks so much for reporting this. Please do let us know if this fix works for you and we'll go ahead and close this issue.

**Comment by hekto** [comment]
Looks good! Thanks.
