### ISSUE TITLE
Make append newline a user setting

### ISSUE THREAD

**Issue by hekto** [thousandtyone/autoend#2]
Personally I would like for the command to never insert newlines, but everyone is different, I guess.. :)

Make it configurable perhaps?

**Comment by thousandtyone** [comment]
I agree. Configurable parameters are always better. I'll work on this and will include it in the next build. Thanks for reporting this.

**Comment by thousandtyone** [comment]
This enhancement has been completed. New code committed and a new version has been pushed on Visual Studio Code Marketplace. 

There is now a setting called autoend.autoInsertNewline which you can override in your VS Code Workspace or User Settings. The default is true but if you don't want the plugin to automatically add a new line and move you to the newline you can override this setting to false. If the setting is false the command will just move you to the end of the current line instead of adding a new line and moving you there. I hope that works.

Note: We only read this setting on activation which means you'll have to restart VS Code each time you change this setting.

Can you please try this out and close this issue if this works for you?

The exact version that has this enhancement in the Visual Studio Code marketplace is 1.0.16.

As always, thanks a lot for reporting this.

For the benefit of folks who might be new to VS Code: Settings can be changed using File / Preferences / Settings.

**Comment by thousandtyone** [comment]
This was updated sometime ago. 

@hekto - Since we have not heard back from you on this we're going ahead and closing the issue. Please feel free to validate and re-open if you continue to face issues with the implementation.
